default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mensore1121
  host: localhost

development:
  <<: *default
  database: sauna_development

test:
  <<: *default
  database: sauna_test

production:
  <<: *default
  database: sauna_production
